---
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - app_network

  api:
    image: ghcr.io/3xCaffeine/rag-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data: